name: sen_app_latest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  file_picker: ^8.0.6
  dio: ^5.5.0+1
  flutter_switch: ^0.3.2
  video_player: ^2.9.1
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
